# Generated by Django 4.1 on 2022-08-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['created'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
